Algoritmo "Soma"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Ele faz a soma de dois valores
// Autor(a)    : Gean Almeida
// Data atual  : 11/03/2024
Var
// Seção de Declarações das variáveis 
   valor1:inteiro
    valor2:inteiro
    soma:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval ("Digite o primeiro valor: ")
leia(valor1)
escreval ("Digite o segundo valor: ")
leia(valor2)
soma <- valor1 + valor2
escreva("A soma dos valores digitados é ",soma)


Fimalgoritmo